;;; casual-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from casual.el

(register-definition-prefixes "casual" '("casual-"))


;;; Generated autoloads from casual-agenda.el

 (autoload 'casual-agenda-tmenu "casual-agenda" nil t)


;;; Generated autoloads from casual-agenda-settings.el

(register-definition-prefixes "casual-agenda-settings" '("casual-agenda-"))


;;; Generated autoloads from casual-agenda-utils.el

(register-definition-prefixes "casual-agenda-utils" '("casual-agenda-"))


;;; Generated autoloads from casual-bookmarks.el

 (autoload 'casual-bookmarks-tmenu "casual-bookmarks" nil t)
(register-definition-prefixes "casual-bookmarks" '("casual-bookmarks-"))


;;; Generated autoloads from casual-bookmarks-settings.el

(register-definition-prefixes "casual-bookmarks-settings" '("casual-bookmarks-"))


;;; Generated autoloads from casual-bookmarks-utils.el

(register-definition-prefixes "casual-bookmarks-utils" '("casual-bookmarks-unicode-"))


;;; Generated autoloads from casual-calc.el

 (autoload 'casual-calc-tmenu "casual-calc" nil t)


;;; Generated autoloads from casual-calc--calc.el

(register-definition-prefixes "casual-calc--calc" '("casual-calc--"))


;;; Generated autoloads from casual-calc-algebra.el

(register-definition-prefixes "casual-calc-algebra" '("casual-calc-"))


;;; Generated autoloads from casual-calc-binary.el

(register-definition-prefixes "casual-calc-binary" '("casual-calc--"))


;;; Generated autoloads from casual-calc-fileio.el

(register-definition-prefixes "casual-calc-fileio" '("casual-calc-"))


;;; Generated autoloads from casual-calc-financial.el

(register-definition-prefixes "casual-calc-financial" '("casual-calc--fin-"))


;;; Generated autoloads from casual-calc-graphics.el

(register-definition-prefixes "casual-calc-graphics" '("casual-calc--"))


;;; Generated autoloads from casual-calc-labels.el

(register-definition-prefixes "casual-calc-labels" '("casual-calc-"))


;;; Generated autoloads from casual-calc-predicates.el

(register-definition-prefixes "casual-calc-predicates" '("casual-calc-"))


;;; Generated autoloads from casual-calc-random.el

(register-definition-prefixes "casual-calc-random" '("casual-calc--random-interval-0-to-m"))


;;; Generated autoloads from casual-calc-settings.el

(register-definition-prefixes "casual-calc-settings" '("casual-calc-"))


;;; Generated autoloads from casual-calc-stack.el

(register-definition-prefixes "casual-calc-stack" '("casual-calc-"))


;;; Generated autoloads from casual-calc-utils.el

(register-definition-prefixes "casual-calc-utils" '("casual-calc-"))


;;; Generated autoloads from casual-calc-vector.el

(register-definition-prefixes "casual-calc-vector" '("casual-calc--histogram"))


;;; Generated autoloads from casual-dired.el

 (autoload 'casual-dired-tmenu "casual-dired" nil t)
(register-definition-prefixes "casual-dired" '("casual-dired-"))


;;; Generated autoloads from casual-dired-settings.el

(register-definition-prefixes "casual-dired-settings" '("casual-dired-"))


;;; Generated autoloads from casual-dired-sort-by.el

(register-definition-prefixes "casual-dired-sort-by" '("casual-dired--"))


;;; Generated autoloads from casual-dired-utils.el

(register-definition-prefixes "casual-dired-utils" '("casual-dired-unicode-"))


;;; Generated autoloads from casual-dired-variables.el

(register-definition-prefixes "casual-dired-variables" '("casual-dired-"))


;;; Generated autoloads from casual-editkit.el

 (autoload 'casual-editkit-main-tmenu "casual-editkit" nil t)


;;; Generated autoloads from casual-editkit-constants.el

(register-definition-prefixes "casual-editkit-constants" '("casual-editkit-"))


;;; Generated autoloads from casual-editkit-settings.el

(register-definition-prefixes "casual-editkit-settings" '("casual-editkit-about"))


;;; Generated autoloads from casual-editkit-utils.el

(register-definition-prefixes "casual-editkit-utils" '("casual-editkit-"))


;;; Generated autoloads from casual-ibuffer.el

 (autoload 'casual-ibuffer-tmenu "casual-ibuffer" nil t)


;;; Generated autoloads from casual-ibuffer-filter.el

(register-definition-prefixes "casual-ibuffer-filter" '("casual-ibuffer-"))


;;; Generated autoloads from casual-ibuffer-settings.el

(register-definition-prefixes "casual-ibuffer-settings" '("casual-ibuffer-"))


;;; Generated autoloads from casual-ibuffer-utils.el

(register-definition-prefixes "casual-ibuffer-utils" '("casual-ibuffer-"))


;;; Generated autoloads from casual-info.el

 (autoload 'casual-info-tmenu "casual-info" nil t)
(register-definition-prefixes "casual-info" '("casual-info-new-info-frame"))


;;; Generated autoloads from casual-info-settings.el

(register-definition-prefixes "casual-info-settings" '("casual-info-"))


;;; Generated autoloads from casual-info-utils.el

(register-definition-prefixes "casual-info-utils" '("casual-info-"))


;;; Generated autoloads from casual-info-variables.el

(register-definition-prefixes "casual-info-variables" '("casual-info-use-unicode-symbols"))


;;; Generated autoloads from casual-isearch.el

(register-definition-prefixes "casual-isearch" '("casual-isearch--toggle-"))


;;; Generated autoloads from casual-isearch-settings.el

(register-definition-prefixes "casual-isearch-settings" '("casual-isearch-"))


;;; Generated autoloads from casual-isearch-utils.el

(register-definition-prefixes "casual-isearch-utils" '("casual-isearch-unicode-"))


;;; Generated autoloads from casual-lib.el

(register-definition-prefixes "casual-lib" '("casual-lib-"))


;;; Generated autoloads from casual-re-builder.el

 (autoload 'casual-re-builder-tmenu "casual-re-builder" nil t)


;;; Generated autoloads from casual-re-builder-settings.el

(register-definition-prefixes "casual-re-builder-settings" '("casual-re-builder-"))


;;; Generated autoloads from casual-re-builder-utils.el

(register-definition-prefixes "casual-re-builder-utils" '("casual-re-builder-"))

;;; End of scraped data

(provide 'casual-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; casual-autoloads.el ends here
