;;; disk-usage-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from disk-usage.el

(autoload 'disk-usage "disk-usage" "\
Display listing of files in DIRECTORY with their size.
If DIRECTORY is nil, use current directory.

(fn &optional DIRECTORY)" t)
(autoload 'disk-usage-here "disk-usage" "\
Run `disk-usage' in current directory." t)
(autoload 'disk-usage-by-types "disk-usage" "\


(fn &optional DIRECTORY)" t)
(autoload 'disk-usage-by-types-here "disk-usage" "\
Run `disk-usage-by-types' in current directory." t)
(register-definition-prefixes "disk-usage" '("disk-usage-"))

;;; End of scraped data

(provide 'disk-usage-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; disk-usage-autoloads.el ends here
