;;; elvish-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elvish-mode.el

(autoload 'elvish-mode "elvish-mode" "\
Major mode for the Elvish language

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.elv\\'" . elvish-mode))
(register-definition-prefixes "elvish-mode" '("elvish-"))

;;; End of scraped data

(provide 'elvish-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elvish-mode-autoloads.el ends here
