# .bashrc is only executed for non-interactive shells

# If not running interactively, don't do anything: special case for remote
# shells.
[[ $- != *i* ]] && return

[[ -f ~/.bash_profile ]] && . ~/.bash_profile
