# -*- mode: shell-script; -*-
#
# .bash_profile is executed for interactive login shells. 

# shared non-Bash sh-type shell configuration:
[[ -f ~/.profile ]] && . ~/.profile

PS1="[\u@\h:\W]\$ "

# history configuration
shopt -s histappend
HISTFILE="${HOME}/.dotfiles/private/history-files/bash_history_$(hostname -s)"
HISTFILESIZE=100000
HISTCONTROL=ignorespace:ignoredups:erasedups
# attempt to fix broken multiline history handling (still broken in bash version < 5, see https://askubuntu.com/a/1210371)
shopt -s cmdhist
shopt -s lithist
# force timestamps into the history file _and_ force multiline history separation in bash version >= 5
HISTTIMEFORMAT="%F %T "
# force history flush on every command (zsh-style), see https://unix.stackexchange.com/a/18443/459230
# note the various versions of this are quite buggy!
#PROMPT_COMMAND="history -a; history -r; $PROMPT_COMMAND"
#PROMPT_COMMAND="history -n; history -w; history -c; history -r; $PROMPT_COMMAND"

# fzf with custom multi-shell history search:
if [[ $(command -v fzf) && $(command -v fzf-history-all) ]]; then
    fzf-history-all-widget () {
        local selected=$(fzf-history-all bash)
        READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
        READLINE_POINT=$(( READLINE_POINT + ${#selected} ))
    }
    bind -x '"\er":fzf-history-all-widget'
fi

# bash version >4 only:
if ((BASH_VERSINFO[0] > 3)); then
    shopt -s autocd
fi

# bash version <5 warning:
if ((BASH_VERSINFO[0] < 5)); then
    echo "warning: bash version < 5 detected; multiline history will not work between sessions" 1>&2
fi
