;;; consult-denote-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-denote.el

(autoload 'consult-denote-grep "consult-denote" "\
Call `consult-denote-grep-command' in the variable `denote-directory'." t)
(function-put 'consult-denote-grep 'interactive-only 't)
(autoload 'consult-denote-find "consult-denote" "\
Call `consult-denote-find-command' in the variable `denote-directory'." t)
(function-put 'consult-denote-find 'interactive-only 't)
(defvar consult-denote-mode nil "\
Non-nil if Consult-Denote mode is enabled.
See the `consult-denote-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `consult-denote-mode'.")
(custom-autoload 'consult-denote-mode "consult-denote" nil)
(autoload 'consult-denote-mode "consult-denote" "\
Use Consult in tandem with Denote.

This is a global minor mode.  If called interactively, toggle the
`Consult-Denote mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='consult-denote-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "consult-denote" '("consult-denote-"))

;;; End of scraped data

(provide 'consult-denote-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-denote-autoloads.el ends here
