;;; poporg-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from poporg.el

(autoload 'poporg-dwim "poporg" "\
Single overall command for poporg (a single keybinding may do it all).

If the current buffer is an edit buffer, run `poporg-edit-exit'.

If the region is active, edit it in an empty buffer.  Otherwise, find a nearby
string or comment using `poporg-find-string-or-comment' and edit that in an
empty buffer.  If there is an active edit nearby, pop to its other buffer and
edit that instead." t)
(autoload 'poporg-update "poporg" "\
Update the contents of the original buffer.

If prefix argument WITH-SAVE is non-nil, save the original buffer too.

Also update the overlay.

(fn WITH-SAVE)" t)
(autoload 'poporg-update-and-save "poporg" "\
Update and save the original buffer; update the region." t)
(autoload 'poporg-edit-exit "poporg" "\
Exit the edit buffer, replacing the original region." t)
(register-definition-prefixes "poporg" '("poporg-"))

;;; End of scraped data

(provide 'poporg-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; poporg-autoloads.el ends here
