;;; casual-avy-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from casual-avy.el

 (autoload 'casual-avy-tmenu "casual-avy" nil t)
(register-definition-prefixes "casual-avy" '("casual-avy-"))


;;; Generated autoloads from casual-avy-version.el

(register-definition-prefixes "casual-avy-version" '("casual-avy-version"))

;;; End of scraped data

(provide 'casual-avy-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; casual-avy-autoloads.el ends here
