theme = "night_owl"

[editor]
auto-pairs = false
#cursorline = true
#scrolloff = 0
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-encoding"]
#center = []
right = ["diagnostics", "selections", "position", "position-percentage"]
#separator = "│"
