theme = "night_owl"

[editor]
soft-wrap = { enable = true }
auto-pairs = false
#auto-save = true
#bufferline = "never"
bufferline = "multiple"
#cursorline = true
line-number = "relative"
#scrolloff = 0
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-encoding"]
#center = []
right = ["file-modification-indicator", "spacer", "diagnostics", "selections", "position", "spacer", "position-percentage"]
#separator = "│"

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.insert]
# jk exits insert mode instead of having to reach for Esc
j = { k = "normal_mode" }
